import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import theme from "./theme";
import { ThemeProvider } from '@mui/material/styles';
import { Provider } from "react-redux";
import { store } from "@/Store/Store";
import UserRedux from "@/Components/UserRedux";
import Navbar from "@/Components/Navbar/Navbar";
import toast, { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
       <UserRedux>
        <Navbar/>
        <Toaster />
        {children}
        </UserRedux>
        </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
